services:
  admin_panel:
    container_name: admin_panel
    build:
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - .env:/var/www/.env:ro
    networks:
      - application-network

  admin_panel_nginx:
    image: nginx:stable-alpine
    container_name: admin_panel_nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT:-800}:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./docker/nginx/http.conf:/etc/nginx/templates/http.conf
      - ./docker/nginx/https.conf:/etc/nginx/templates/https.conf
      - ./docker/nginx/entrypoint.sh:/entrypoint.sh
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
    entrypoint: ["/bin/sh", "/entrypoint.sh"]

    networks:
      - application-network

  mysql:
    image: docker.arvancloud.ir/mysql:latest
    container_name: mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - application-network

  phpmyadmin:
    image: docker.arvancloud.ir/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "3390:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - application-network

  redis:
    image: docker.arvancloud.ir/redis
    container_name: redis_db
    volumes:
      - redis_data:/data
    networks:
      - application-network

networks:
  application-network:
    driver: bridge

volumes:
  redis_data:
  mysql_data:
